const SECONDS = 1000
const MINUTE_IN_SECONDS = 60 * SECONDS
const HOUR_IN_SECONDS = 60 * MINUTE_IN_SECONDS
const DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS
const WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS
const MONTH_IN_SECONDS = 30 * DAY_IN_SECONDS
const YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS

export {
    SECONDS,
    MINUTE_IN_SECONDS,
    HOUR_IN_SECONDS,
    DAY_IN_SECONDS,
    WEEK_IN_SECONDS,
    MONTH_IN_SECONDS,
    YEAR_IN_SECONDS,
}

export const EVENTS = {
    VIEW_CHANGE: 'view-change',
    SORT_CHANGE: 'sort-change',
    NOTIFICATION_RECEIVED: 'notification-received',
    NOTIFICATION_CLICK: 'notification-click',
    DOCUMENT_ADDED: 'document-added',
}
